---
# TODO: need to figure out a plan for setting hostname, currently the default
# is localhost, so no hostname value (or public_hostname) value is getting
# assigned
- include: ../../common/openshift-cluster/config.yml
  vars_files:
  - ../../libvirt/openshift-cluster/vars.yml
  - ../../libvirt/openshift-cluster/cluster_hosts.yml
  vars:
    g_ssh_user: "{{ deployment_vars[deployment_type].ssh_user }}"
    g_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    g_nodeonmaster: true
    openshift_cluster_id: "{{ cluster_id }}"
    openshift_debug_level: "{{ debug_level }}"
    openshift_deployment_type: "{{ deployment_type }}"
    openshift_registry_selector: 'type=infra'
    openshift_router_selector: 'type=infra'
    openshift_infra_nodes: "{{ g_infra_hosts }}"
    openshift_master_cluster_method: 'native'
    openshift_use_openshift_sdn: "{{ lookup('oo_option', 'use_openshift_sdn') }}"
    os_sdn_network_plugin_name: "{{ lookup('oo_option', 'sdn_network_plugin_name') }}"
    openshift_use_flannel: "{{ lookup('oo_option', 'use_flannel') }}"
    openshift_use_fluentd: "{{ lookup('oo_option', 'use_fluentd') }}"
    openshift_pkg_version: -3.0.2.0
    openshift_additional_repos:
    - id: ose
      name: ose
      baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/ose/3.0/os
      enabled: 1
      gpgcheck: 0
    - id: rhel7
      name: rhel7
      baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
      enabled: 1
      gpgcheck: 0
    - id: rhel7-extras
      name: rhel7-extras
      baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/extras/os
      enabled: 1
      gpgcheck: 0

