---
- name: Populate oo_hosts_to_update group
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
  - vars.yml
  - cluster_hosts.yml
  tasks:
  - name: Evaluate oo_hosts_to_update
    add_host:
      name: "{{ item }}"
      groups: oo_hosts_to_update
      ansible_ssh_user: "{{ deployment_vars[deployment_type].ssh_user }}"
      ansible_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    with_items: "{{ g_all_hosts | default([]) }}"

- include: ../../common/openshift-cluster/update_repos_and_packages.yml
  vars:
    openshift_additional_repos:
    - id: ose
      name: ose
      baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/ose/3.0/os
      enabled: 1
      gpgcheck: 0
    - id: rhel7
      name: rhel7
      baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
      enabled: 1
      gpgcheck: 0
    - id: rhel7-extras
      name: rhel7-extras
      baseurl: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/x86_64/extras/os
      enabled: 1
      gpgcheck: 0

- include: config.yml
