---
sudo: false

language: python

python:
  - "2.7"
  - "3.5"

cache:
  - pip

before_cache:
  - rm ~/.cache/pip/log/debug.log

env:
  - TEST_DIR=. TEST_TYPE=lint
  - TEST_DIR=. TEST_TYPE=unit
  - TEST_DIR=utils

install:
  - pip install tox-travis

script:
  - cd "${TEST_DIR}" && tox
