---
sudo: false

cache:
  - pip

before_cache:
  - rm ~/.cache/pip/log/debug.log

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - jdetiber@redhat.com
      - sdodson@redhat.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - chat.freenode.net#openshift-dev
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "sdodson jdetiber: ^"
