---
- include: ../../../../common/openshift-cluster/upgrades/v3_0_to_v3_1/upgrade.yml
  vars_files:
  - ../../../../byo/openshift-cluster/cluster_hosts.yml
  vars:
    openshift_cluster_id: "{{ cluster_id | default('default') }}"
    openshift_deployment_type: "{{ deployment_type }}"
