---
- name: Set docker facts
  openshift_facts:
    role: docker
    local_facts:
      portal_net: "{{ openshift_master_portal_net | default(None) }}"
      log_driver:  "{{ openshift_docker_log_driver
                       | default(lookup('oo_option' , 'docker_log_driver')
                                 | default(None ,True)) }}"
      log_options: "{{ openshift_docker_log_options
                       | default(lookup('oo_option' , 'docker_log_options')
                                 | default(None, True)) }}"
      extra_options: "{{ openshift_docker_extra_options
                         | default(lookup('oo_option', 'docker_extra_options')
                                   | default(None, True)) }}"
      additional_registries: "{{ openshift_docker_additional_registries
                                 | default(lookup('oo_option', 'docker_additional_registries')
                                           | default(None, True)) }}"
      insecure_registries: "{{ openshift_docker_insecure_registries
                               | default(lookup('oo_option', 'docker_insecure_registries')
                                         | default(None, True)) }}"
      blocked_registries: "{{ openshift_docker_blocked_registries
                              | default(lookup('oo_option', 'docker_blocked_registries')
                                        | default(None, True)) }}"

- stat: path=/etc/sysconfig/docker
  register: docker_check

- name: Set registry params
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^{{ item.reg_conf_var }}=.*$'
    line: "{{ item.reg_conf_var }}='{{ item.reg_fact_val | oo_prepend_strings_in_list(item.reg_flag ~ ' ') | join(' ') }}'"
  when: item.reg_fact_key in openshift.docker and docker_check.stat.isreg
  with_items:
  - reg_conf_var: ADD_REGISTRY
    reg_fact_key: additional_registries
    reg_fact_val: "{{ openshift.docker.additional_registries }}"
    reg_flag: --add-registry
  - reg_conf_var: BLOCK_REGISTRY
    reg_fact_key: blocked_registries
    reg_fact_val: "{{ openshift.docker.blocked_registries }}"
    reg_flag: --block-registry
  - reg_conf_var: INSECURE_REGISTRY
    reg_fact_key: insecure_registries
    reg_fact_val: "{{ openshift.docker.insecure_registries }}"
    reg_flag: --insecure-registry
  notify:
  - restart openshift_docker

# TODO: Enable secure registry when code available in origin
# TODO: perhaps move this to openshift_docker?
- name: Secure Registry and Logs Options
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^OPTIONS=.*$'
    line: "OPTIONS='{{ docker_opts }}'"
  when: docker_check.stat.isreg
  notify:
    - restart openshift_docker
