---
- name: Set docker facts
  openshift_facts:
    role: "{{ item.role }}"
    local_facts: "{{ item.local_facts }}"
  with_items:
  - role: docker
    local_facts:
      additional_registries: "{{ openshift_docker_additional_registries | default(None) }}"
      blocked_registries: "{{ openshift_docker_blocked_registries | default(None) }}"
      insecure_registries: "{{ openshift_docker_insecure_registries | default(None) }}"
      log_driver:  "{{ openshift_docker_log_driver | default(None) }}"
      log_options: "{{ openshift_docker_log_options | default(None) }}"
      options: "{{ openshift_docker_options | default(None) }}"
      disable_push_dockerhub: "{{ openshift_disable_push_dockerhub | default(None) }}"
  - role: node
    local_facts:
      portal_net: "{{ openshift_master_portal_net | default(None) }}"

# TODO: append openshift.node.portal_net to docker_insecure_registries
- set_fact:
    docker_additional_registries: "{{ openshift.docker.additional_registries
                                      | default(omit) }}"
    docker_blocked_registries: "{{ openshift.docker.blocked_registries
                                   | default(omit) }}"
    docker_insecure_registries: "{{ openshift.docker.insecure_registries
                                    | default(omit) }}"
    docker_log_driver: "{{ openshift.docker.log_driver | default(omit) }}"
    docker_log_options: "{{ openshift.docker.log_options | default(omit) }}"
    docker_options: "{{ openshift.docker.options | default(omit) }}"
    docker_push_dockerhub: "{{ openshift.docker.disable_push_dockerhub
                               | default(omit) }}"
