---
# TODO: fix firewall related bug with GCE and origin, since GCE is overriding
# /etc/sysconfig/iptables
- include: ../../common/openshift-cluster/config.yml
  vars_files:
  - ../../gce/openshift-cluster/vars.yml
  - ../../gce/openshift-cluster/cluster_hosts.yml
  vars:
    g_ssh_user: "{{ lookup('env', 'gce_ssh_user') | default(deployment_vars[deployment_type].ssh_user, true) }}"
    g_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    g_nodeonmaster: true
    openshift_cluster_id: "{{ cluster_id }}"
    openshift_debug_level: "{{ debug_level }}"
    openshift_deployment_type: "{{ deployment_type }}"
    openshift_hostname: "{{ gce_private_ip }}"
    openshift_use_openshift_sdn: "{{ do_we_use_openshift_sdn }}"
    os_sdn_network_plugin_name: "{{ sdn_network_plugin }}"
    openshift_router_selector: 'type=infra'
    osm_infra_nodes: "{{ g_infra_hosts }}"
